version: "3.7"

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest

    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181
    expose:
      - 2181
    logging:
      options:
        max-size: 2m
    networks:
      network:
        aliases:
          - zookeeper
  kafka:
    # image: wurstmeister/kafka:latest
    image: kafka:1.0
    command: bash -c start-kafka.sh

    build:
      context: .
      dockerfile: kafka.Dockerfile
    container_name: kafka
    restart: always
    ports:
      - 9092:9092
    expose:
      - 9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CREATE_TOPICS=local_access_log:1:1,apiv4-results:1:1,scan:1:1
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper.kafka-network:2181
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:19092,EXTERNAL://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://localhost:19092,EXTERNAL://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL

    logging:
      options:
        max-size: 2m
    networks:
      network:
        aliases:
          - kafka
networks:
  network:
    name: kafka-network
